version: '3.3'

services:

  # ------------------------------------
  # App Container
  # ------------------------------------

  podio_api-postgres:
    container_name: podio_api-postgres
    deploy:
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.5'
          memory: 1000M
        limits:
          cpus: '1'
          memory: 3500M
    build:
      context: ./
      dockerfile: Dockerfile
    image: gbvsilva/podio-api:postgres
    env_file:
      - '/home/graco.silva/git/env-files/podio_api/env.bi'
      - '/home/graco.silva/git/env-files/gn_databases/env.gn_dw'
