version: '3.3'

services:

  # ------------------------------------
  # App Container
  # ------------------------------------

  podio_api-mysql:
    container_name: podio_api-mysql
    deploy:
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.5'
          memory: 1000M
        limits:
          cpus: '1'
          memory: 3500M
    build:
      context: ./
      dockerfile: Dockerfile
    image: gbvsilva/podio-api:mysql
    env_file:
      - '/home/graco.silva/git/env-files/podio_api/env.bi'
    network_mode: host
