version: '3.3'

services:

  # ------------------------------------
  # App Container
  # ------------------------------------

  podio_api:
    container_name: podio_api
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1000M
        limits:
          cpus: '1'
          memory: 1000M
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: gbvsilva/podio_api
    env_file:
      - "${PODIO_API_ENVFILE}"
      - "${DATABASE_ENVFILE}"
      - "${MISC_ENVFILE}"
      - "${TELEGRAM_ENVFILE}"
    volumes:
      - ./:/opt/podio_api
