version: '3.3'

services:

  # ------------------------------------
  # App Container
  # ------------------------------------

  podio_api-mysql:
    container_name: podio_api-mysql
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1000M
        limits:
          cpus: '1'
          memory: 3500M
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:3
    image: gbvsilva/podio-api:mysql
    env_file:
      - '/home/graco.silva/git/env-files/podio_api/bi.env'
      - '/home/graco.silva/git/env-files/databases/graco_local.env'
      - '/home/graco.silva/git/env-files/misc/local.env'
      - '/home/graco.silva/git/env-files/telegram/podio_api_aux_bot.env'
    network_mode: host
